config/routes.rb
Rails.application.routes.draw do
  root 'flights#index'
  resources :seats
  resources :flights
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flight.rb
class Flight < ApplicationRecord
  has_many :seats
end

app/models/seat.rb
class Seat < ApplicationRecord
  belongs_to :flight

  validate :validate_baggage_allowance

  private

  def validate_baggage_allowance
    errors.add(:base, 'You have too much baggage') if baggage > flight.baggage_allowance
    return unless flight.seats.size >= flight.capacity

    errors.add(:base, 'The flight is fully booked')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: %i[show edit update destroy]

  # GET /flights or /flights.json
  def index
    @flights = Flight.all
  end

  # GET /flights/1 or /flights/1.json
  def show; end

  # GET /flights/new
  def new
    @flight = Flight.new
  end

  # GET /flights/1/edit
  def edit; end

  # POST /flights or /flights.json
  def create
    @flight = Flight.new(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to flight_url(@flight), notice: 'Flight was successfully created.' }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1 or /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to flight_url(@flight), notice: 'Flight was successfully updated.' }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1 or /flights/1.json
  def destroy
    @flight.destroy

    respond_to do |format|
      format.html { redirect_to flights_url, notice: 'Flight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_flight
    @flight = Flight.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def flight_params
    params.require(:flight).permit(:departure, :arrival, :destination, :baggage_allowance, :capacity)
  end
end

app/controllers/seats_controller.rb
class SeatsController < ApplicationController
  before_action :set_seat, only: %i[show edit update destroy]

  # GET /seats or /seats.json
  def index
    @seats = Seat.all
  end

  # GET /seats/1 or /seats/1.json
  def show; end

  # GET /seats/new
  def new
    @seat = Seat.new
  end

  # GET /seats/1/edit
  def edit; end

  # POST /seats or /seats.json
  def create
    @seat = Seat.new(seat_params)

    respond_to do |format|
      if @seat.save
        format.html { redirect_to seat_url(@seat), notice: 'Seat was successfully created.' }
        format.json { render :show, status: :created, location: @seat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @seat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seats/1 or /seats/1.json
  def update
    respond_to do |format|
      if @seat.update(seat_params)
        format.html { redirect_to seat_url(@seat), notice: 'Seat was successfully updated.' }
        format.json { render :show, status: :ok, location: @seat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @seat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seats/1 or /seats/1.json
  def destroy
    @seat.destroy

    respond_to do |format|
      format.html { redirect_to seats_url, notice: 'Seat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_seat
    @seat = Seat.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def seat_params
    params.require(:seat).permit(:flight_id, :name, :baggage)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/views/flights/_flight.html.erb
<div id="<%= dom_id flight %>">
  <p>
    <strong>Departure:</strong>
    <%= flight.departure %>
  </p>

  <p>
    <strong>Arrival:</strong>
    <%= flight.arrival %>
  </p>

  <p>
    <strong>Destination:</strong>
    <%= flight.destination %>
  </p>

  <p>
    <strong>Baggage allowance:</strong>
    <%= flight.baggage_allowance %>
  </p>

  <p>
    <strong>Capacity:</strong>
    <%= flight.capacity %>
  </p>

</div>

app/views/flights/_form.html.erb
<%= form_with(model: flight) do |form| %>
  <% if flight.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
        <% flight.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :departure, style: "display: block" %>
    <%= form.date_field :departure %>
  </div>

  <div>
    <%= form.label :arrival, style: "display: block" %>
    <%= form.date_field :arrival %>
  </div>

  <div>
    <%= form.label :destination, style: "display: block" %>
    <%= form.text_field :destination %>
  </div>

  <div>
    <%= form.label :baggage_allowance, style: "display: block" %>
    <%= form.text_field :baggage_allowance %>
  </div>

  <div>
    <%= form.label :capacity, style: "display: block" %>
    <%= form.number_field :capacity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/flights/_new_seat.html.erb
<h1>New seat</h1>

<%= render "seat_form", seat: Seat.new(flight_id: @flight.id) %>

<br>

app/views/flights/_seat_form.html.erb
<%= form_with(model: seat) do |form| %>
    <% if seat.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(seat.errors.count, "error") %> prohibited this seat from being saved:</h2>
  
        <ul>
          <% seat.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.hidden_field :flight_id %>
    </div>
    
    <div>
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name %>
    </div>
  
    <div>
      <%= form.label :baggage, style: "display: block" %>
      <%= form.text_field :baggage %>
    </div>
  
    <div>
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/flights/_seats_list.html.erb
<h2>List of seats</h2>

<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Baggage</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <% for seat in seats %>
            <tr>
                <td><%=h seat.name %></td>
                <td><%=h seat.baggage %></td>
                <td>
                    <%= link_to "Show this seat", seat %>
                    <%= link_to 'Edit', edit_seat_path(seat) %>
                    <%= button_to "Destroy this seat", seat, method: :delete %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/flights/edit.html.erb
<h1>Editing flight</h1>

<%= render "form", flight: @flight %>

<br>

<div>
  <%= link_to "Show this flight", @flight %> |
  <%= link_to "Back to flights", flights_path %>
</div>

app/views/flights/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Flights</h1>

<div id="flights">
  <% @flights.each do |flight| %>
    <%= render flight %>
    <p>
      <%= link_to "Show this flight", flight %>
    </p>
  <% end %>
</div>

<%= link_to "New flight", new_flight_path %>

app/views/flights/new.html.erb
<h1>New flight</h1>

<%= render "form", flight: @flight %>

<br>

<div>
  <%= link_to "Back to flights", flights_path %>
</div>

app/views/flights/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @flight %>

<%= render 'seats_list', seats: @flight.seats %>

<%= render :partial=>"new_seat" %>

<div>
  <%= link_to "Edit this flight", edit_flight_path(@flight) %> |
  <%= link_to "Back to flights", flights_path %>

  <%= button_to "Destroy this flight", @flight, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirlineBookingSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/seats/_form.html.erb
<%= form_with(model: seat) do |form| %>
  <% if seat.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(seat.errors.count, "error") %> prohibited this seat from being saved:</h2>

      <ul>
        <% seat.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :flight_id, style: "display: block" %>
    <%= form.number_field :flight_id %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :baggage, style: "display: block" %>
    <%= form.text_field :baggage %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/seats/_seat.html.erb
<div id="<%= dom_id seat %>">
  <p>
    <strong>Flight:</strong>
    <%= seat.flight_id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= seat.name %>
  </p>

  <p>
    <strong>Baggage:</strong>
    <%= seat.baggage %>
  </p>

</div>

app/views/seats/edit.html.erb
<h1>Editing seat</h1>

<%= render "form", seat: @seat %>

<br>

<div>
  <%= link_to "Show this seat", @seat %> |
  <%= link_to "Back to seats", seats_path %>
</div>

app/views/seats/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Seats</h1>

<div id="seats">
  <% @seats.each do |seat| %>
    <%= render seat %>
    <p>
      <%= link_to "Show this seat", seat %>
    </p>
  <% end %>
</div>

<%= link_to "New seat", new_seat_path %>

app/views/seats/new.html.erb
<h1>New seat</h1>

<%= render "form", seat: @seat %>

<br>

<div>
  <%= link_to "Back to seats", seats_path %>
</div>

app/views/seats/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @seat %>

<div>
  <%= link_to "Edit this seat", edit_seat_path(@seat) %> |
  <%= link_to "Back to seats", seats_path %>

  <%= button_to "Destroy this seat", @seat, method: :delete %>
</div>